# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Install with Maven
      run: mvn install -DskipTests -Dgpg.skip --quiet
    - name: Compile with Maven
      run: mvn clean compile assembly:single
    - name: Spotless check
      run: mvn spotless:check
    - name: FrontendTests
      run: mvn -Dtest=FrontendTests test
    - name: RuntimeTests
      run: mvn -Dtest=RuntimeTests test
    - name: SparkRuntimeTests
      run: mvn -Dtest=SparkRuntimeTests test
    - name: StaticTypeTests
      run: mvn -Dtest=StaticTypeTests test
    - name: NativeFLWORRuntimeTests
      run: mvn -Dtest=NativeFLWORRuntimeTests test
    - name: JavaAPITest
      run: mvn -Dtest=JavaAPITest test
    - name: Install Spark and run server tests
      run: mkdir -p /opt; wget -q -O /opt/spark.tgz https://downloads.apache.org/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz ; tar -xzf /opt/spark.tgz -C /opt/ ; rm /opt/spark.tgz ; export SPARK_HOME=/opt/spark-2.4.5-bin-hadoop2.7 ; export PATH=$PATH:/opt/spark-2.4.5-bin-hadoop2.7/bin; bash server-test-script.sh
    - name: Copying artefacts
      run: mkdir staging && cp target/*.jar staging
    - name: Package
      uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
